# Generated by Django 4.2.2 on 2023-06-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='asunto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='telefono',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
