# Generated by Django 4.2.2 on 2023-06-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0005_alter_contactmessage_contactado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='contactado',
            field=models.BooleanField(default=False),
        ),
    ]
