# Generated by Django 4.2.2 on 2023-06-28 02:44

from django.db import migrations, models
import eventos.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_alter_page_image1_alter_page_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image6',
            field=models.ImageField(null=True, upload_to=eventos.models.image_upload_path, verbose_name='Imagen 6'),
        ),
    ]
